server:
  port: 8081

spring:
  application:
    name: pokemon-service

  datasource:
    url: jdbc:mysql://localhost:3306/pokemon_db?useSSL=false&serverTimezone=UTC
    username: mpc
    password: mpc
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8701/eureka/
  instance:
    prefer-ip-address: true
